name: Publish Release
on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

env:
    APP_NAME: 'DCI - Eco Atlantic'

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
        needs: changelog
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # build the changelog based on the commit messages between the versioned tags

            - name: Setup Node.js
              uses: actions/setup-node@v4
              # NOTE: enterprise developers may hard code a version
              with:
                  node-version-file: '.nvmrc'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Setup Rust
              run: |
                  rustup update --no-self-update

            - name: Build frontend
              run: |
                  pnpm install --frozen-lockfile
                  pnpm build

            - name: Build Tauri app
              uses: tauri-apps/tauri-action@v0
              # if u get Error: Resource not accessible by integration
              # go to repository Settings => Action => General => Workflow permissions => Switch to Read and Write permisions
              env:
                  CI: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  # tauri-action replaces \_\_VERSION\_\_ with the app version
                  tagName: ${{ github.ref_name }}
                  releaseName: '${{ env.APP_NAME }} v__VERSION__'
                  releaseBody: |
                      ${{needs.changelog.outputs.changelog}}
                      See the assets to download this version and install.
                  releaseDraft: true
                  prerelease: false
